name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - DacDat
  pull_request:
    branches:
      - DacDat

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Authenticate with Firebase
        uses: FirebaseExtended/action-hosting-deploy@v2
        with:
          firebase_version: "9.x"
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting